/*
 * Travel phrasebook data (RU → EN). Dual export like the farm project's data.js.
 * HYBRID method: topic structure follows the paper book (Victory, 2004), but every
 * English phrase + transcription is re-authored in modern British English (not copied —
 * the book's compiled text is under copyright; topics/words are not).
 *
 * Schema: window.PHRASEBOOK = [{ id, icon, title_ru, phrases:[{ru, en, transcr, sec?}] }]
 * sec (optional) = sub-theme title shown as a divider header before that phrase in the UI
 * (mirrors the book's sub-sections). Only the FIRST phrase of a sub-group carries `sec`.
 * transcr = Cyrillic reading aid (convention: /w/→«у», θ→«с», ð→«з», æ→«э», ŋ→«нг»,
 * final BrE r silent). Categories mirror the book's содержание (see PLAN.md).
 *
 * Status: sections filled progressively. Done so far: greetings, money, customs,
 * directions, transport, hotel, restaurant, shopping, medical, problems, about, time,
 * numbers, colours. Pending: post/phone, service, entertainment, education, measures.
 */
(function (root) {
  const PHRASEBOOK = [
    {
      id: "greetings",
      icon: "👋",
      title_ru: "Приветствия и знакомство",
      phrases: [
        // — Приветствие —
        { sec: "Приветствие", ru: "Здравствуйте.", en: "Hello.", transcr: "хэлоу" },
        { ru: "Привет.", en: "Hi.", transcr: "хай" },
        { ru: "Доброе утро.", en: "Good morning.", transcr: "гуд монин" },
        { ru: "Добрый день.", en: "Good afternoon.", transcr: "гуд афтэнун" },
        { ru: "Добрый вечер.", en: "Good evening.", transcr: "гуд ивнин" },
        { ru: "Как дела?", en: "How are you?", transcr: "хау а ю" },
        { ru: "Хорошо, спасибо. А вы?", en: "Fine, thanks. And you?", transcr: "файн сэнкс, энд ю" },
        { ru: "Как поживаете?", en: "How's it going?", transcr: "хауз ит гоуин" },
        // — Знакомство —
        { sec: "Знакомство", ru: "Как вас зовут?", en: "What's your name?", transcr: "уотс ё нэйм" },
        { ru: "Меня зовут…", en: "My name is…", transcr: "май нэйм из" },
        { ru: "Приятно познакомиться.", en: "Nice to meet you.", transcr: "найс тэ мит ю" },
        { ru: "Мне тоже приятно.", en: "Nice to meet you too.", transcr: "найс тэ мит ю ту" },
        { ru: "Откуда вы?", en: "Where are you from?", transcr: "уэа а ю фром" },
        { ru: "Я из…", en: "I'm from…", transcr: "айм фром" },
        { ru: "Вы говорите по-русски?", en: "Do you speak Russian?", transcr: "ду ю спик рашн" },
        // — Вежливость —
        { sec: "Вежливость", ru: "Спасибо.", en: "Thank you.", transcr: "сэнк ю" },
        { ru: "Большое спасибо.", en: "Thank you very much.", transcr: "сэнк ю вэри мач" },
        { ru: "Пожалуйста (в ответ).", en: "You're welcome.", transcr: "ё уэлкэм" },
        { ru: "Пожалуйста (просьба).", en: "Please.", transcr: "плиз" },
        { ru: "Извините.", en: "Sorry.", transcr: "сори" },
        { ru: "Простите (чтобы обратиться).", en: "Excuse me.", transcr: "икскьюз ми" },
        { ru: "Ничего страшного.", en: "No problem.", transcr: "ноу проблэм" },
        { ru: "Да. / Нет.", en: "Yes. / No.", transcr: "йес / ноу" },
        { ru: "Я не понимаю.", en: "I don't understand.", transcr: "ай доунт андэстэнд" },
        { ru: "Повторите, пожалуйста.", en: "Could you say that again, please?", transcr: "куд ю сэй зэт эгэн плиз" },
        // — Просьба и приглашение —
        { sec: "Просьба и приглашение", ru: "Можно вас попросить?", en: "Can I ask you a favour?", transcr: "кэн ай аск ю э фэйвэ" },
        { ru: "Не могли бы вы мне помочь?", en: "Could you help me?", transcr: "куд ю хэлп ми" },
        { ru: "Хотите кофе?", en: "Would you like a coffee?", transcr: "вуд ю лайк э кофи" },
        { ru: "Пойдёмте с нами.", en: "Come with us.", transcr: "кам уиз ас" },
        { ru: "Давайте встретимся завтра.", en: "Let's meet tomorrow.", transcr: "летс мит тэмороу" },
        // — Согласие и отказ —
        { sec: "Согласие и отказ", ru: "Хорошо, договорились.", en: "OK, that's a deal.", transcr: "оукэй зэтс э дил" },
        { ru: "Я согласен.", en: "I agree.", transcr: "ай эгри" },
        { ru: "С удовольствием.", en: "With pleasure.", transcr: "уиз плэжэ" },
        { ru: "Может быть.", en: "Maybe.", transcr: "мэйби" },
        { ru: "Боюсь, что нет.", en: "I'm afraid not.", transcr: "айм эфрэйд нот" },
        { ru: "Нет, спасибо.", en: "No, thank you.", transcr: "ноу сэнк ю" },
        // — Поздравления и пожелания —
        { sec: "Поздравления и пожелания", ru: "Поздравляю!", en: "Congratulations!", transcr: "кэнгрэчулэйшнз" },
        { ru: "С днём рождения!", en: "Happy birthday!", transcr: "хэпи бёсдэй" },
        { ru: "С Новым годом!", en: "Happy New Year!", transcr: "хэпи нью йиэ" },
        { ru: "Счастливого пути!", en: "Have a good trip!", transcr: "хэв э гуд трип" },
        { ru: "Удачи!", en: "Good luck!", transcr: "гуд лак" },
        { ru: "Приятного аппетита!", en: "Enjoy your meal!", transcr: "инджой ё мил" },
        // — Сочувствие и поддержка —
        { sec: "Сочувствие и поддержка", ru: "Мне очень жаль.", en: "I'm so sorry.", transcr: "айм соу сори" },
        { ru: "Не волнуйтесь.", en: "Don't worry.", transcr: "доунт уори" },
        { ru: "Всё будет хорошо.", en: "It'll be all right.", transcr: "итл би ол райт" },
        { ru: "Выздоравливайте.", en: "Get well soon.", transcr: "гет уэл сун" },
        { ru: "Не переживайте.", en: "Never mind.", transcr: "нэвэ майнд" },
        // — Прощание —
        { sec: "Прощание", ru: "До свидания.", en: "Goodbye.", transcr: "гудбай" },
        { ru: "Пока. / Увидимся!", en: "Bye. / See you!", transcr: "бай / си ю" },
        { ru: "Спокойной ночи.", en: "Good night.", transcr: "гуд найт" },
        { ru: "Берегите себя.", en: "Take care.", transcr: "тэйк кэа" },
        { ru: "Было приятно познакомиться.", en: "It was nice meeting you.", transcr: "ит уоз найс митин ю" },
      ],
    },
    {
      id: "customs",
      icon: "🛂",
      title_ru: "Паспортный контроль и таможня",
      phrases: [
        // — Паспортный контроль —
        { sec: "Паспортный контроль", ru: "Вот мой паспорт.", en: "Here's my passport.", transcr: "хиэз май паспот" },
        { ru: "Я здесь как турист.", en: "I'm here on holiday.", transcr: "айм хиэ он холидэй" },
        { ru: "Я здесь по работе.", en: "I'm here on business.", transcr: "айм хиэ он бизнэс" },
        { ru: "Я здесь проездом.", en: "I'm just passing through.", transcr: "айм джаст пасин сру" },
        { ru: "Я пробуду две недели.", en: "I'm staying for two weeks.", transcr: "айм стэйин фо ту уикс" },
        { ru: "Я остановлюсь в отеле.", en: "I'm staying at a hotel.", transcr: "айм стэйин эт э хоутэл" },
        { ru: "Вот моя бронь.", en: "Here's my booking.", transcr: "хиэз май букин" },
        { ru: "Вот обратный билет.", en: "Here's my return ticket.", transcr: "хиэз май ритён тикит" },
        { ru: "Я здесь впервые.", en: "It's my first time here.", transcr: "итс май фёст тайм хиэ" },
        // — Таможня —
        { sec: "Таможня", ru: "Мне нечего декларировать.", en: "I have nothing to declare.", transcr: "ай хэв насин тэ диклэа" },
        { ru: "Это мои личные вещи.", en: "These are my personal belongings.", transcr: "зиз а май пёснэл билонгинз" },
        { ru: "Это подарок.", en: "It's a gift.", transcr: "итс э гифт" },
        { ru: "Это для личного пользования.", en: "It's for personal use.", transcr: "итс фо пёснэл юз" },
        { ru: "Мне нужно это декларировать?", en: "Do I need to declare this?", transcr: "ду ай нид тэ диклэа зис" },
        { ru: "Помогите заполнить бланк, пожалуйста.", en: "Could you help me fill in the form?", transcr: "куд ю хэлп ми фил ин зэ фом" },
        // — Багаж —
        { sec: "Багаж", ru: "Где выдача багажа?", en: "Where's the baggage reclaim?", transcr: "уэаз зэ бэгидж риклэйм" },
        { ru: "Это мой чемодан.", en: "This is my suitcase.", transcr: "зис из май сюткейс" },
        { ru: "Мой чемодан не приехал.", en: "My suitcase hasn't arrived.", transcr: "май сюткейс хэзнт эрайвд" },
        { ru: "Одной сумки не хватает.", en: "One of my bags is missing.", transcr: "уан оф май бэгз из мисин" },
        { ru: "Осторожнее с этой сумкой.", en: "Be careful with that bag.", transcr: "би кэафул уиз зэт бэг" },
        { ru: "Мне нужна тележка для багажа.", en: "I need a luggage trolley.", transcr: "ай нид э лагидж троли" },
        // — После контроля —
        { sec: "После контроля", ru: "Где я могу взять такси?", en: "Where can I get a taxi?", transcr: "уэа кэн ай гет э такси" },
        { ru: "Где обмен валюты?", en: "Where's the bureau de change?", transcr: "уэаз зэ бюроу дэ шонж" },
        { ru: "Где выход?", en: "Where's the exit?", transcr: "уэаз зэ эксит" },
      ],
    },
    {
      id: "transport",
      icon: "🚌",
      title_ru: "Транспорт",
      phrases: [
        // — Билеты и справки —
        { sec: "Билеты и справки", ru: "Где можно купить билет?", en: "Where can I buy a ticket?", transcr: "уэа кэн ай бай э тикит" },
        { ru: "Один билет до…, пожалуйста.", en: "A ticket to…, please.", transcr: "э тикит тэ … плиз" },
        { ru: "Мне туда и обратно.", en: "A return ticket, please.", transcr: "э ритён тикит плиз" },
        { ru: "Мне в одну сторону.", en: "A single, please.", transcr: "э сингл плиз" },
        { ru: "Сколько стоит билет до…?", en: "How much is a ticket to…?", transcr: "хау мач из э тикит тэ" },
        { ru: "Во сколько отправление?", en: "What time does it leave?", transcr: "уот тайм даз ит лив" },
        { ru: "Где справочное бюро?", en: "Where's the information desk?", transcr: "уэаз зи инфэмэйшн дэск" },
        { ru: "Можно расписание?", en: "Could I have a timetable?", transcr: "куд ай хэв э таймтэйбл" },
        // — Автобус —
        { sec: "Автобус", ru: "Где ближайшая остановка?", en: "Where's the nearest bus stop?", transcr: "уэаз зэ ниэрэст бас стоп" },
        { ru: "Этот автобус идёт до центра?", en: "Does this bus go to the centre?", transcr: "даз зис бас гоу тэ зэ сэнтэ" },
        { ru: "Какой автобус идёт до…?", en: "Which bus goes to…?", transcr: "уич бас гоуз тэ" },
        { ru: "Вы принимаете карты?", en: "Do you take cards?", transcr: "ду ю тэйк кадз" },
        { ru: "Скажите, когда мне выходить?", en: "Could you tell me when to get off?", transcr: "куд ю тэл ми уэн тэ гет оф" },
        { ru: "Я выхожу на следующей.", en: "I'm getting off at the next stop.", transcr: "айм гетин оф эт зэ нэкст стоп" },
        // — Метро (the Underground) —
        { sec: "Метро (the Underground)", ru: "Можно карту метро?", en: "Could I have a Tube map?", transcr: "куд ай хэв э тьюб мэп" },
        { ru: "Какая линия идёт до…?", en: "Which line goes to…?", transcr: "уич лайн гоуз тэ" },
        { ru: "Где мне сделать пересадку?", en: "Where do I change?", transcr: "уэа ду ай чэйндж" },
        { ru: "Сколько остановок до…?", en: "How many stops is it to…?", transcr: "хау мэни стопс из ит тэ" },
        { ru: "Можно приложить карту?", en: "Can I tap my card?", transcr: "кэн ай тэп май кад" },
        // — Поезд —
        { sec: "Поезд", ru: "С какой платформы поезд до…?", en: "Which platform for the train to…?", transcr: "уич плэтфом фо зэ трэйн тэ" },
        { ru: "Этот поезд останавливается в…?", en: "Does this train stop at…?", transcr: "даз зис трэйн стоп эт" },
        { ru: "Это место занято?", en: "Is this seat taken?", transcr: "из зис сит тэйкэн" },
        { ru: "Простите, это моё место.", en: "Excuse me, this is my seat.", transcr: "икскьюз ми, зис из май сит" },
        { ru: "Какая следующая станция?", en: "What's the next station?", transcr: "уотс зэ нэкст стэйшн" },
        { ru: "Мы опаздываем?", en: "Are we running late?", transcr: "а уи ранин лэйт" },
        { ru: "Поезд задерживается.", en: "The train's delayed.", transcr: "зэ трэйнз дилэйд" },
        // — Такси —
        { sec: "Такси", ru: "Где стоянка такси?", en: "Where's the taxi rank?", transcr: "уэаз зэ такси рэнк" },
        { ru: "Вы свободны?", en: "Are you free?", transcr: "а ю фри" },
        { ru: "Отвезите меня по этому адресу.", en: "Take me to this address, please.", transcr: "тэйк ми тэ зис эдрэс плиз" },
        { ru: "Сколько до аэропорта?", en: "How much is it to the airport?", transcr: "хау мач из ит тэ зи эапот" },
        { ru: "Включите счётчик, пожалуйста.", en: "Could you put the meter on?", transcr: "куд ю пут зэ митэ он" },
        { ru: "Остановите здесь, пожалуйста.", en: "Stop here, please.", transcr: "стоп хиэ плиз" },
        { ru: "Сдачи не надо.", en: "Keep the change.", transcr: "кип зэ чэйндж" },
        // — Самолёт и аэропорт —
        { sec: "Самолёт и аэропорт", ru: "Где стойка регистрации?", en: "Where's the check-in desk?", transcr: "уэаз зэ чек-ин дэск" },
        { ru: "Вот мой паспорт и билет.", en: "Here's my passport and ticket.", transcr: "хиэз май паспот энд тикит" },
        { ru: "Место у окна, пожалуйста.", en: "A window seat, please.", transcr: "э уиндоу сит плиз" },
        { ru: "Место у прохода, пожалуйста.", en: "An aisle seat, please.", transcr: "эн айл сит плиз" },
        { ru: "У меня только ручная кладь.", en: "I only have hand luggage.", transcr: "ай оунли хэв хэнд лагидж" },
        { ru: "К какому выходу мне идти?", en: "Which gate do I go to?", transcr: "уич гэйт ду ай гоу тэ" },
        { ru: "Во сколько посадка?", en: "What time is boarding?", transcr: "уот тайм из бодин" },
        { ru: "Мой рейс задержали.", en: "My flight's been delayed.", transcr: "май флайтс бин дилэйд" },
      ],
    },
    {
      id: "directions",
      icon: "🗺️",
      title_ru: "В городе: как пройти",
      phrases: [
        // — Как спросить дорогу —
        { sec: "Как спросить дорогу", ru: "Извините, как пройти к…?", en: "Excuse me, how do I get to…?", transcr: "икскьюз ми, хау ду ай гет тэ" },
        { ru: "Я ищу этот адрес.", en: "I'm looking for this address.", transcr: "айм лукин фо зис эдрэс" },
        { ru: "Где находится…?", en: "Where is…?", transcr: "уэа из" },
        { ru: "Это далеко?", en: "Is it far?", transcr: "из ит фа" },
        { ru: "Это близко?", en: "Is it near?", transcr: "из ит ниэ" },
        { ru: "Как лучше туда добраться?", en: "What's the best way to get there?", transcr: "уотс зэ бэст уэй тэ гет зэа" },
        { ru: "Туда можно дойти пешком?", en: "Can I walk there?", transcr: "кэн ай уок зэа" },
        { ru: "Мне лучше поехать на автобусе?", en: "Should I take the bus?", transcr: "шуд ай тэйк зэ бас" },
        { ru: "Покажите на карте, пожалуйста.", en: "Could you show me on the map?", transcr: "куд ю шоу ми он зэ мэп" },
        // — Что вам ответят —
        { sec: "Что вам ответят", ru: "Идите прямо.", en: "Go straight ahead.", transcr: "гоу стрэйт эхэд" },
        { ru: "Поверните налево.", en: "Turn left.", transcr: "тён лэфт" },
        { ru: "Поверните направо.", en: "Turn right.", transcr: "тён райт" },
        { ru: "На углу.", en: "On the corner.", transcr: "он зэ конэ" },
        { ru: "Напротив парка.", en: "Opposite the park.", transcr: "опэзит зэ пак" },
        { ru: "Рядом с площадью.", en: "Near the square.", transcr: "ниэ зэ сквэа" },
        { ru: "За зданием.", en: "Behind the building.", transcr: "бихайнд зэ билдин" },
        { ru: "Это в двух минутах.", en: "It's two minutes away.", transcr: "итс ту минитс эвэй" },
        // — Осмотр города —
        { sec: "Осмотр города", ru: "Где центр города?", en: "Where's the town centre?", transcr: "уэаз зэ таун сэнтэ" },
        { ru: "Где ближайшая станция метро?", en: "Where's the nearest Tube station?", transcr: "уэаз зэ ниэрэст тьюб стэйшн" },
        { ru: "Где туристический центр?", en: "Where's the tourist information centre?", transcr: "уэаз зэ туэрист инфэмэйшн сэнтэ" },
        { ru: "Есть экскурсии по городу?", en: "Is there a guided tour of the city?", transcr: "из зэа э гайдэд туэ оф зэ сити" },
        { ru: "Что стоит посмотреть в первую очередь?", en: "What's worth seeing first?", transcr: "уотс уёс сиин фёст" },
        { ru: "Я заблудился.", en: "I'm lost.", transcr: "айм лост" },
      ],
    },
    {
      id: "hotel",
      icon: "🏨",
      title_ru: "Гостиница",
      phrases: [
        // — Заселение —
        { sec: "Заселение", ru: "У меня забронирован номер.", en: "I have a reservation.", transcr: "ай хэв э рэзэвэйшн" },
        { ru: "Бронь на фамилию…", en: "The booking is under the name…", transcr: "зэ букин из андэ зэ нэйм" },
        { ru: "У вас есть свободные номера?", en: "Do you have any rooms available?", transcr: "ду ю хэв эни румз эвэйлэбл" },
        { ru: "Одноместный номер, пожалуйста.", en: "A single room, please.", transcr: "э сингл рум плиз" },
        { ru: "Двухместный номер, пожалуйста.", en: "A double room, please.", transcr: "э дабл рум плиз" },
        { ru: "Номер с ванной.", en: "A room with a bathroom.", transcr: "э рум уиз э басрум" },
        { ru: "На две ночи.", en: "For two nights.", transcr: "фо ту найтс" },
        { ru: "Сколько стоит за ночь?", en: "How much is it per night?", transcr: "хау мач из ит пё найт" },
        { ru: "Завтрак включён?", en: "Is breakfast included?", transcr: "из брэкфэст инклудид" },
        { ru: "Можно посмотреть номер?", en: "Could I see the room?", transcr: "куд ай си зэ рум" },
        { ru: "Вот мой паспорт.", en: "Here's my passport.", transcr: "хиэз май паспот" },
        { ru: "На каком этаже мой номер?", en: "Which floor is my room on?", transcr: "уич фло из май рум он" },
        // — Где что в отеле —
        { sec: "Где что в отеле", ru: "Скажите, где лифт?", en: "Where's the lift, please?", transcr: "уэаз зэ лифт плиз" },
        { ru: "Где ресторан?", en: "Where's the restaurant?", transcr: "уэаз зэ рэстрон" },
        { ru: "Где бар?", en: "Where's the bar?", transcr: "уэаз зэ ба" },
        { ru: "Где бассейн?", en: "Where's the swimming pool?", transcr: "уэаз зэ суимин пул" },
        { ru: "Где тренажёрный зал?", en: "Where's the gym?", transcr: "уэаз зэ джим" },
        { ru: "Где парикмахерская?", en: "Where's the hairdresser's?", transcr: "уэаз зэ хэадрэсэз" },
        { ru: "Где можно припарковать машину?", en: "Where can I park my car?", transcr: "уэа кэн ай пак май ка" },
        { ru: "В номере есть Wi-Fi?", en: "Is there Wi-Fi in the room?", transcr: "из зэа уай-фай ин зэ рум" },
        // — Просьбы к персоналу —
        { sec: "Просьбы к персоналу", ru: "Ключ от номера, пожалуйста.", en: "The room key, please.", transcr: "зэ рум ки плиз" },
        { ru: "Отнесите мой багаж наверх, пожалуйста.", en: "Could you take my luggage up, please?", transcr: "куд ю тэйк май лагидж ап плиз" },
        { ru: "Можно ещё одно полотенце?", en: "Could I have an extra towel?", transcr: "куд ай хэв эн экстрэ тауэл" },
        { ru: "Можно ещё одеяло?", en: "Could I have an extra blanket?", transcr: "куд ай хэв эн экстрэ блэнкит" },
        { ru: "Можно ещё подушку?", en: "Could I have an extra pillow?", transcr: "куд ай хэв эн экстрэ пилоу" },
        { ru: "Разбудите меня в семь, пожалуйста.", en: "Could I have a wake-up call at seven?", transcr: "куд ай хэв э уэйк-ап кол эт сэвн" },
        { ru: "Уберите номер, пожалуйста.", en: "Could you clean the room, please?", transcr: "куд ю клин зэ рум плиз" },
        { ru: "Мне нужны мыло и шампунь.", en: "I need soap and shampoo.", transcr: "ай нид соуп энд шампу" },
        // — Жалобы —
        { sec: "Жалобы", ru: "В номере нет горячей воды.", en: "There's no hot water.", transcr: "зэаз ноу хот уотэ" },
        { ru: "Кондиционер не работает.", en: "The air conditioning isn't working.", transcr: "зи эа кэндишнин изнт уёкин" },
        { ru: "Отопление не работает.", en: "The heating isn't working.", transcr: "зэ хитин изнт уёкин" },
        { ru: "В номере холодно.", en: "The room is cold.", transcr: "зэ рум из коулд" },
        { ru: "Слишком шумно.", en: "It's too noisy.", transcr: "итс ту нойзи" },
        { ru: "Свет не работает.", en: "The light isn't working.", transcr: "зэ лайт изнт уёкин" },
        { ru: "Можно поменять номер?", en: "Could I change rooms?", transcr: "куд ай чэйндж румз" },
        // — Отъезд —
        { sec: "Отъезд", ru: "Я уезжаю завтра.", en: "I'm checking out tomorrow.", transcr: "айм чекин аут тэмороу" },
        { ru: "Во сколько выселение?", en: "What time is check-out?", transcr: "уот тайм из чек-аут" },
        { ru: "Подготовьте счёт, пожалуйста.", en: "Could you prepare my bill, please?", transcr: "куд ю припэа май бил плиз" },
        { ru: "Сколько с меня?", en: "How much is the bill?", transcr: "хау мач из зэ бил" },
        { ru: "Мне кажется, в счёте ошибка.", en: "I think there's a mistake in the bill.", transcr: "ай синк зэаз э мистэйк ин зэ бил" },
        { ru: "Вызовите такси, пожалуйста.", en: "Could you order a taxi, please?", transcr: "куд ю одэ э такси плиз" },
        { ru: "Можно оставить багаж до вечера?", en: "Could I leave my luggage until this evening?", transcr: "куд ай лив май лагидж энтил зис ивнин" },
        { ru: "Спасибо, обслуживание было прекрасным.", en: "Thank you, the service was excellent.", transcr: "сэнк ю, зэ сёвис уоз эксэлэнт" },
      ],
    },
    {
      id: "money",
      icon: "💱",
      title_ru: "Деньги и обмен валюты",
      phrases: [
        // — Обмен валюты —
        { sec: "Обмен валюты", ru: "Где можно обменять деньги?", en: "Where can I change money?", transcr: "уэа кэн ай чэйндж мани" },
        { ru: "Где ближайший обменный пункт?", en: "Where's the nearest bureau de change?", transcr: "уэаз зэ ниэрэст бюроу дэ шонж" },
        { ru: "Какой курс обмена?", en: "What's the exchange rate?", transcr: "уотс зи иксчэйндж рэйт" },
        { ru: "Я хочу обменять доллары на фунты.", en: "I'd like to change dollars into pounds.", transcr: "айд лайк тэ чэйндж долэз интэ паундз" },
        { ru: "Есть ли комиссия?", en: "Is there a commission?", transcr: "из зэа э кэмишн" },
        { ru: "Мелкими купюрами, пожалуйста.", en: "In small notes, please.", transcr: "ин смол ноутс плиз" },
        // — Банкомат и карта —
        { sec: "Банкомат и карта", ru: "Где ближайший банкомат?", en: "Where's the nearest cash machine?", transcr: "уэаз зэ ниэрэст кэш мэшин" },
        { ru: "Банкомат не принял мою карту.", en: "The cash machine didn't accept my card.", transcr: "зэ кэш мэшин диднт эксэпт май кад" },
        { ru: "Можно оплатить картой?", en: "Can I pay by card?", transcr: "кэн ай пэй бай кад" },
        { ru: "Здесь принимают карты?", en: "Do you take cards here?", transcr: "ду ю тэйк кадз хиэ" },
        { ru: "Я заплачу наличными.", en: "I'll pay in cash.", transcr: "айл пэй ин кэш" },
        { ru: "У вас есть сдача?", en: "Have you got any change?", transcr: "хэв ю гот эни чэйндж" },
        // — Оплата и цены —
        { sec: "Оплата и цены", ru: "Сколько это стоит?", en: "How much is it?", transcr: "хау мач из ит" },
        { ru: "Сколько всего?", en: "How much is that altogether?", transcr: "хау мач из зэт олтэгэзэ" },
        { ru: "Это слишком дорого.", en: "That's too expensive.", transcr: "зэтс ту икспэнсив" },
        { ru: "Кажется, это неправильно.", en: "I think that's wrong.", transcr: "ай синк зэтс ронг" },
        { ru: "Можно счёт пополам?", en: "Can we split the bill?", transcr: "кэн уи сплит зэ бил" },
        { ru: "Дайте, пожалуйста, чек.", en: "Could I have a receipt, please?", transcr: "куд ай хэв э рисит плиз" },
      ],
    },
    {
      id: "restaurant",
      icon: "🍽️",
      title_ru: "Ресторан и еда",
      phrases: [
        // — Посадка —
        { sec: "Посадка", ru: "Столик на двоих, пожалуйста.", en: "A table for two, please.", transcr: "э тэйбл фо ту плиз" },
        { ru: "У нас забронирован столик.", en: "We have a booking.", transcr: "уи хэв э букин" },
        { ru: "Можно сесть у окна?", en: "Could we sit by the window?", transcr: "куд уи сит бай зэ уиндоу" },
        { ru: "Меню, пожалуйста.", en: "The menu, please.", transcr: "зэ мэню плиз" },
        { ru: "У вас есть меню на английском?", en: "Do you have a menu in English?", transcr: "ду ю хэв э мэню ин инглиш" },
        // — Заказ —
        { sec: "Заказ", ru: "Что вы посоветуете?", en: "What do you recommend?", transcr: "уот ду ю рэкэмэнд" },
        { ru: "Какое у вас фирменное блюдо?", en: "What's the speciality?", transcr: "уотс зэ спэшэлити" },
        { ru: "Я буду вот это.", en: "I'll have this.", transcr: "айл хэв зис" },
        { ru: "Мне то же самое.", en: "The same for me.", transcr: "зэ сэйм фо ми" },
        { ru: "На закуску…", en: "For starters…", transcr: "фо статэз" },
        { ru: "На горячее…", en: "For the main course…", transcr: "фо зэ мэйн кос" },
        { ru: "На десерт…", en: "For dessert…", transcr: "фо дизёт" },
        { ru: "Ещё хлеба, пожалуйста.", en: "Some more bread, please.", transcr: "сам мо брэд плиз" },
        // — Диета —
        { sec: "Диета", ru: "Я вегетарианец.", en: "I'm vegetarian.", transcr: "айм вэджитэриэн" },
        { ru: "У меня аллергия на орехи.", en: "I'm allergic to nuts.", transcr: "айм элёджик тэ натс" },
        { ru: "Без лука, пожалуйста.", en: "No onions, please.", transcr: "ноу аньэнз плиз" },
        { ru: "Это острое?", en: "Is this spicy?", transcr: "из зис спайси" },
        // — Приборы —
        { sec: "Приборы", ru: "Вилка.", en: "A fork.", transcr: "э фок" },
        { ru: "Нож.", en: "A knife.", transcr: "э найф" },
        { ru: "Ложка.", en: "A spoon.", transcr: "э спун" },
        { ru: "Тарелка.", en: "A plate.", transcr: "э плэйт" },
        { ru: "Стакан.", en: "A glass.", transcr: "э глас" },
        { ru: "Салфетка.", en: "A napkin.", transcr: "э нэпкин" },
        { ru: "Можно чистую вилку?", en: "Could I have a clean fork?", transcr: "куд ай хэв э клин фок" },
        // — Приправы —
        { sec: "Приправы", ru: "Соль и перец.", en: "Salt and pepper.", transcr: "солт энд пэпэ" },
        { ru: "Сахар.", en: "Sugar.", transcr: "шугэ" },
        { ru: "Масло (растительное).", en: "Oil.", transcr: "ойл" },
        { ru: "Соус.", en: "Sauce.", transcr: "сос" },
        // — Способы приготовления —
        { sec: "Способы приготовления", ru: "Жареное (на сковороде).", en: "Fried.", transcr: "фрайд" },
        { ru: "Варёное.", en: "Boiled.", transcr: "бойлд" },
        { ru: "На гриле.", en: "Grilled.", transcr: "грилд" },
        { ru: "Запечённое.", en: "Roasted.", transcr: "роустид" },
        { ru: "Хорошо прожаренное.", en: "Well done.", transcr: "уэл дан" },
        { ru: "С кровью (мясо).", en: "Rare.", transcr: "рэа" },
        // — Напитки —
        { sec: "Напитки", ru: "Воды, пожалуйста.", en: "Some water, please.", transcr: "сам уотэ плиз" },
        { ru: "Чай / кофе.", en: "Tea / coffee.", transcr: "ти / кофи" },
        { ru: "Сок.", en: "Juice.", transcr: "джус" },
        { ru: "Бокал вина.", en: "A glass of wine.", transcr: "э глас оф уайн" },
        { ru: "Кружку пива.", en: "A pint of beer.", transcr: "э пайнт оф биэ" },
        // — Оплата —
        { sec: "Оплата", ru: "Это очень вкусно.", en: "This is delicious.", transcr: "зис из дэлишэс" },
        { ru: "Счёт, пожалуйста.", en: "The bill, please.", transcr: "зэ бил плиз" },
        { ru: "Обслуживание включено?", en: "Is service included?", transcr: "из сёвис инклудид" },
        { ru: "Мне кажется, в счёте ошибка.", en: "I think there's a mistake in the bill.", transcr: "ай синк зэаз э мистэйк ин зэ бил" },
        { ru: "Можно оплатить картой?", en: "Can I pay by card?", transcr: "кэн ай пэй бай кад" },
      ],
    },
    {
      id: "shopping",
      icon: "🛍️",
      title_ru: "Покупки",
      phrases: [
        // — Общее —
        { sec: "Общее", ru: "Я просто смотрю, спасибо.", en: "I'm just looking, thanks.", transcr: "айм джаст лукин, сэнкс" },
        { ru: "Сколько это стоит?", en: "How much is this?", transcr: "хау мач из зис" },
        { ru: "У вас есть…?", en: "Do you have…?", transcr: "ду ю хэв" },
        { ru: "Покажите вот это, пожалуйста.", en: "Could you show me that one, please?", transcr: "куд ю шоу ми зэт уан плиз" },
        { ru: "Мне это нравится.", en: "I like this one.", transcr: "ай лайк зис уан" },
        { ru: "Я это возьму.", en: "I'll take it.", transcr: "айл тэйк ит" },
        { ru: "Во сколько вы закрываетесь?", en: "What time do you close?", transcr: "уот тайм ду ю клоуз" },
        // — Одежда и обувь —
        { sec: "Одежда и обувь", ru: "Можно примерить?", en: "Can I try it on?", transcr: "кэн ай трай ит он" },
        { ru: "Где примерочная?", en: "Where's the fitting room?", transcr: "уэаз зэ фитин рум" },
        { ru: "Мой размер — …", en: "I'm a size…", transcr: "айм э сайз" },
        { ru: "Это слишком большое.", en: "It's too big.", transcr: "итс ту биг" },
        { ru: "Это слишком маленькое.", en: "It's too small.", transcr: "итс ту смол" },
        { ru: "У вас есть побольше?", en: "Have you got a bigger one?", transcr: "хэв ю гот э бигэ уан" },
        { ru: "У вас есть поменьше?", en: "Have you got a smaller one?", transcr: "хэв ю гот э смолэ уан" },
        { ru: "А другого цвета есть?", en: "Do you have it in another colour?", transcr: "ду ю хэв ит ин эназэ калэ" },
        { ru: "Это натуральная кожа?", en: "Is it real leather?", transcr: "из ит риэл лэзэ" },
        // — Продукты —
        { sec: "Продукты", ru: "Где ближайший супермаркет?", en: "Where's the nearest supermarket?", transcr: "уэаз зэ ниэрэст супэмакит" },
        { ru: "Где здесь тележки?", en: "Where are the trolleys?", transcr: "уэар а зэ тролиз" },
        { ru: "Бутылку воды, пожалуйста.", en: "A bottle of water, please.", transcr: "э ботл оф уотэ плиз" },
        { ru: "Батон хлеба, пожалуйста.", en: "A loaf of bread, please.", transcr: "э лоуф оф брэд плиз" },
        { ru: "Литр молока.", en: "A litre of milk.", transcr: "э литэ оф милк" },
        { ru: "Немного фруктов, пожалуйста.", en: "Some fruit, please.", transcr: "сам фрут плиз" },
        { ru: "Это всё, спасибо.", en: "That's all, thanks.", transcr: "зэтс ол сэнкс" },
        { ru: "Можно пакет?", en: "Can I have a bag, please?", transcr: "кэн ай хэв э бэг плиз" },
        // — Сувениры и подарки —
        { sec: "Сувениры и подарки", ru: "Я ищу подарок.", en: "I'm looking for a gift.", transcr: "айм лукин фо э гифт" },
        { ru: "Что-нибудь типично британское.", en: "Something typically British.", transcr: "самсин типикли бритиш" },
        { ru: "У вас есть открытки?", en: "Do you have any postcards?", transcr: "ду ю хэв эни поусткадз" },
        { ru: "Это ручная работа?", en: "Is it handmade?", transcr: "из ит хэндмэйд" },
        { ru: "Можно упаковать как подарок?", en: "Could you gift-wrap it?", transcr: "куд ю гифт-рэп ит" },
        // — Оплата —
        { sec: "Оплата", ru: "Это слишком дорого.", en: "It's too expensive.", transcr: "итс ту икспэнсив" },
        { ru: "У вас есть что-нибудь подешевле?", en: "Have you got anything cheaper?", transcr: "хэв ю гот энисин чипэ" },
        { ru: "Можно скидку?", en: "Is there any discount?", transcr: "из зэа эни дискаунт" },
        { ru: "Вы принимаете карты?", en: "Do you take cards?", transcr: "ду ю тэйк кадз" },
        { ru: "Можно приложить карту?", en: "Can I pay contactless?", transcr: "кэн ай пэй контэктлэс" },
        { ru: "Дайте, пожалуйста, чек.", en: "Could I have a receipt, please?", transcr: "куд ай хэв э рисит плиз" },
        { ru: "Кажется, вы дали неправильную сдачу.", en: "I think you've given me the wrong change.", transcr: "ай синк юв гивэн ми зэ ронг чэйндж" },
        { ru: "Можно это вернуть?", en: "Can I return this?", transcr: "кэн ай ритён зис" },
        { ru: "Где касса?", en: "Where's the till?", transcr: "уэаз зэ тил" },
      ],
    },
    {
      id: "entertainment",
      icon: "🎭",
      title_ru: "Развлечения и отдых",
      phrases: [
        // — Досуг и увлечения —
        { sec: "Досуг и увлечения", ru: "Чем вы увлекаетесь?", en: "What are your hobbies?", transcr: "уот а ё хобиз" },
        { ru: "Как вы проводите свободное время?", en: "What do you do in your free time?", transcr: "уот ду ю ду ин ё фри тайм" },
        { ru: "Я люблю путешествовать.", en: "I like travelling.", transcr: "ай лайк трэвлин" },
        { ru: "Я люблю фотографировать.", en: "I like photography.", transcr: "ай лайк фэтогрэфи" },
        { ru: "Я люблю читать.", en: "I like reading.", transcr: "ай лайк ридин" },
        { ru: "Что здесь стоит посмотреть?", en: "What is there to see here?", transcr: "уот из зэа тэ си хиэ" },
        // — Кино и театр —
        { sec: "Кино и театр", ru: "Что идёт в кино?", en: "What's on at the cinema?", transcr: "уотс он эт зэ синэмэ" },
        { ru: "Я хочу пойти в театр.", en: "I'd like to go to the theatre.", transcr: "айд лайк тэ гоу тэ зэ сиэтэ" },
        { ru: "Где можно купить билеты?", en: "Where can I buy tickets?", transcr: "уэа кэн ай бай тикитс" },
        { ru: "Два билета, пожалуйста.", en: "Two tickets, please.", transcr: "ту тикитс плиз" },
        { ru: "Во сколько начало?", en: "What time does it start?", transcr: "уот тайм даз ит стат" },
        { ru: "Есть билеты на сегодня?", en: "Are there any tickets for tonight?", transcr: "а зэа эни тикитс фо тэнайт" },
        { ru: "Сколько идёт спектакль?", en: "How long does it last?", transcr: "хау лонг даз ит ласт" },
        { ru: "Где мои места?", en: "Where are our seats?", transcr: "уэа а ауэ ситс" },
        // — Ночной клуб —
        { sec: "Ночной клуб", ru: "Где здесь можно потанцевать?", en: "Where can we go dancing?", transcr: "уэа кэн уи гоу дансин" },
        { ru: "Здесь есть хороший бар?", en: "Is there a good bar nearby?", transcr: "из зэа э гуд ба ниэбай" },
        { ru: "Во сколько закрывается?", en: "What time do you close?", transcr: "уот тайм ду ю клоуз" },
        { ru: "Нужно бронировать столик?", en: "Do we need to book a table?", transcr: "ду уи нид тэ бук э тэйбл" },
        // — Музей —
        { sec: "Музей", ru: "Во сколько открывается музей?", en: "What time does the museum open?", transcr: "уот тайм даз зэ мьюзиэм оупэн" },
        { ru: "Сколько стоит вход?", en: "How much is admission?", transcr: "хау мач из эдмишн" },
        { ru: "Здесь можно фотографировать?", en: "Can I take photos here?", transcr: "кэн ай тэйк фоутоуз хиэ" },
        { ru: "Есть экскурсия на английском?", en: "Is there a tour in English?", transcr: "из зэа э туэ ин инглиш" },
        // — На природе и спорт —
        { sec: "На природе и спорт", ru: "Я люблю гулять на природе.", en: "I like being outdoors.", transcr: "ай лайк биин аутдоз" },
        { ru: "Куда ведёт эта тропа?", en: "Where does this path lead?", transcr: "уэа даз зис пас лид" },
        { ru: "Я хочу сходить в бассейн.", en: "I'd like to go to the swimming pool.", transcr: "айд лайк тэ гоу тэ зэ суимин пул" },
        { ru: "Где ближайший спортзал?", en: "Where's the nearest gym?", transcr: "уэаз зэ ниэрэст джим" },
        { ru: "Это было замечательно.", en: "That was wonderful.", transcr: "зэт уоз уандэфул" },
        { ru: "Мне очень понравилось.", en: "I really enjoyed it.", transcr: "ай риэли инджойд ит" },
      ],
    },
    {
      id: "post",
      icon: "📮",
      title_ru: "Почта",
      phrases: [
        // — На почте —
        { sec: "На почте", ru: "Где ближайшая почта?", en: "Where's the nearest post office?", transcr: "уэаз зэ ниэрэст поуст офис" },
        { ru: "Во сколько открывается почта?", en: "What time does the post office open?", transcr: "уот тайм даз зэ поуст офис оупэн" },
        { ru: "Какое окно для посылок?", en: "Which counter is for parcels?", transcr: "уич каунтэ из фо пасэлз" },
        { ru: "Где почтовый ящик?", en: "Where's the postbox?", transcr: "уэаз зэ поустбокс" },
        // — Письма и посылки —
        { sec: "Письма и посылки", ru: "Я хочу отправить письмо.", en: "I'd like to send a letter.", transcr: "айд лайк тэ сэнд э лэтэ" },
        { ru: "Я хочу отправить посылку.", en: "I'd like to send a parcel.", transcr: "айд лайк тэ сэнд э пасл" },
        { ru: "Я хочу отправить это в Россию.", en: "I'd like to send this to Russia.", transcr: "айд лайк тэ сэнд зис тэ раша" },
        { ru: "Сколько весит посылка?", en: "How much does the parcel weigh?", transcr: "хау мач даз зэ пасл уэй" },
        { ru: "Обычной или первым классом?", en: "First or second class?", transcr: "фёст о сэкэнд клас" },
        { ru: "Сколько идёт до России?", en: "How long does it take to Russia?", transcr: "хау лонг даз ит тэйк тэ раша" },
        { ru: "Заказное письмо, пожалуйста.", en: "Recorded delivery, please.", transcr: "рикодид дэливэри плиз" },
        { ru: "Мне нужно отправить срочно.", en: "I need to send this express.", transcr: "ай нид тэ сэнд зис икспрэс" },
        { ru: "Могу я отследить посылку?", en: "Can I track the parcel?", transcr: "кэн ай трэк зэ пасл" },
        // — Марки и открытки —
        { sec: "Марки и открытки", ru: "Сколько стоит марка?", en: "How much is a stamp?", transcr: "хау мач из э стэмп" },
        { ru: "Марку для России, пожалуйста.", en: "A stamp for Russia, please.", transcr: "э стэмп фо раша плиз" },
        { ru: "Пять марок, пожалуйста.", en: "Five stamps, please.", transcr: "файв стэмпс плиз" },
        { ru: "Открытка.", en: "A postcard.", transcr: "э поусткад" },
        { ru: "Где можно купить конверт?", en: "Where can I buy an envelope?", transcr: "уэа кэн ай бай эн энвэлоуп" },
      ],
    },
    {
      id: "phone",
      icon: "📞",
      title_ru: "Телефон и интернет",
      phrases: [
        // — SIM-карта и интернет —
        { sec: "SIM-карта и интернет", ru: "Можно мне SIM-карту?", en: "Can I get a SIM card?", transcr: "кэн ай гет э сим кад" },
        { ru: "Мне нужна туристическая SIM-карта.", en: "I'd like a tourist SIM card.", transcr: "айд лайк э туэрист сим кад" },
        { ru: "Здесь есть мобильный интернет?", en: "Is there mobile data here?", transcr: "из зэа моубайл дэйта хиэ" },
        { ru: "Где есть Wi-Fi?", en: "Where can I find Wi-Fi?", transcr: "уэа кэн ай файнд уай-фай" },
        { ru: "Какой пароль от Wi-Fi?", en: "What's the Wi-Fi password?", transcr: "уотс зэ уай-фай пасуёд" },
        { ru: "Wi-Fi бесплатный?", en: "Is the Wi-Fi free?", transcr: "из зэ уай-фай фри" },
        { ru: "Мне нужно пополнить счёт.", en: "I need to top up my phone.", transcr: "ай нид тэ топ ап май фоун" },
        { ru: "У меня разрядился телефон.", en: "My phone is dead.", transcr: "май фоун из дэд" },
        { ru: "Где можно зарядить телефон?", en: "Where can I charge my phone?", transcr: "уэа кэн ай чадж май фоун" },
        // — Звонок —
        { sec: "Звонок", ru: "Можно позвонить?", en: "Can I make a call?", transcr: "кэн ай мэйк э кол" },
        { ru: "Мне нужно позвонить в Россию.", en: "I need to call Russia.", transcr: "ай нид тэ кол раша" },
        { ru: "Сколько стоит звонок за границу?", en: "How much is an international call?", transcr: "хау мач из эн интэнэшнл кол" },
        { ru: "Какой у вас номер?", en: "What's your number?", transcr: "уотс ё намбэ" },
        { ru: "Я вам перезвоню.", en: "I'll call you back.", transcr: "айл кол ю бэк" },
        { ru: "Пожалуйста, напишите мне сообщение.", en: "Please text me.", transcr: "плиз тэкст ми" },
        // — Разговор по телефону —
        { sec: "Разговор по телефону", ru: "Алло!", en: "Hello?", transcr: "хэлоу" },
        { ru: "Можно поговорить с…?", en: "Could I speak to…?", transcr: "куд ай спик тэ" },
        { ru: "Кто говорит?", en: "Who's calling?", transcr: "хуз колин" },
        { ru: "Одну минуту.", en: "Just a moment.", transcr: "джаст э моумэнт" },
        { ru: "Не вешайте трубку.", en: "Hold on, please.", transcr: "хоулд он плиз" },
        { ru: "Вы можете говорить помедленнее?", en: "Could you speak more slowly?", transcr: "куд ю спик мо слоули" },
        { ru: "Плохая связь.", en: "The line is bad.", transcr: "зэ лайн из бэд" },
        { ru: "Вы ошиблись номером.", en: "You've got the wrong number.", transcr: "юв гот зэ ронг намбэ" },
        { ru: "Можно оставить сообщение?", en: "Can I leave a message?", transcr: "кэн ай лив э мэсидж" },
      ],
    },
    {
      id: "service",
      icon: "✂️",
      title_ru: "Бытовые услуги",
      phrases: [
        // — Парикмахерская —
        { sec: "Парикмахерская", ru: "Мне нужна стрижка.", en: "I'd like a haircut.", transcr: "айд лайк э хэакат" },
        { ru: "Просто подровняйте, пожалуйста.", en: "Just a trim, please.", transcr: "джаст э трим плиз" },
        { ru: "Не очень коротко.", en: "Not too short.", transcr: "нот ту щёт" },
        { ru: "Покороче по бокам.", en: "Shorter on the sides.", transcr: "щётэ он зэ сайдз" },
        { ru: "Оставьте сверху подлиннее.", en: "Leave it longer on top.", transcr: "лив ит лонгэ он топ" },
        { ru: "Побрейте, пожалуйста.", en: "A shave, please.", transcr: "э шэйв плиз" },
        { ru: "Подровняйте бороду.", en: "Trim my beard, please.", transcr: "трим май биэд плиз" },
        { ru: "Помойте и уложите, пожалуйста.", en: "Wash and blow-dry, please.", transcr: "уош энд блоу-драй плиз" },
        // — Прачечная и химчистка —
        { sec: "Прачечная и химчистка", ru: "Где можно постирать вещи?", en: "Where can I do my laundry?", transcr: "уэа кэн ай ду май лондри" },
        { ru: "Мне нужна химчистка.", en: "I need dry cleaning.", transcr: "ай нид драй клинин" },
        { ru: "Можно это погладить?", en: "Can you press this, please?", transcr: "кэн ю прэс зис плиз" },
        { ru: "Здесь пятно.", en: "There's a stain here.", transcr: "зэаз э стэйн хиэ" },
        { ru: "Вы можете вывести это пятно?", en: "Can you remove this stain?", transcr: "кэн ю римув зис стэйн" },
        { ru: "Когда будет готово?", en: "When will it be ready?", transcr: "уэн уил ит би рэди" },
        { ru: "Мне нужно к завтрашнему дню.", en: "I need it by tomorrow.", transcr: "ай нид ит бай тэмороу" },
        // — Ремонт и мастерская —
        { sec: "Ремонт и мастерская", ru: "Вы можете это починить?", en: "Can you repair this?", transcr: "кэн ю рипэа зис" },
        { ru: "У меня сломались часы.", en: "My watch is broken.", transcr: "май уоч из броукэн" },
        { ru: "Мне нужна новая батарейка.", en: "I need a new battery.", transcr: "ай нид э нью бэтэри" },
        { ru: "У меня порвалась обувь.", en: "My shoe is broken.", transcr: "май шу из броукэн" },
        { ru: "Можно поставить набойки?", en: "Can you re-heel these, please?", transcr: "кэн ю ри-хил зиз плиз" },
        { ru: "У меня сломалась молния.", en: "The zip is broken.", transcr: "зэ зип из броукэн" },
        { ru: "Сколько это будет стоить?", en: "How much will it cost?", transcr: "хау мач уил ит кост" },
        { ru: "Когда я могу забрать?", en: "When can I collect it?", transcr: "уэн кэн ай кэлэкт ит" },
      ],
    },
    {
      id: "medical",
      icon: "🏥",
      title_ru: "Медицинская помощь",
      phrases: [
        // — У врача —
        { sec: "У врача", ru: "Мне нужен врач.", en: "I need a doctor.", transcr: "ай нид э доктэ" },
        { ru: "Вызовите врача, скорее!", en: "Get a doctor, quick!", transcr: "гет э доктэ квик" },
        { ru: "Здесь есть врач, говорящий по-русски?", en: "Is there a doctor who speaks Russian?", transcr: "из зэа э доктэ ху спикс рашн" },
        { ru: "Я плохо себя чувствую.", en: "I'm not feeling well.", transcr: "айм нот филин уэл" },
        { ru: "Меня тошнит.", en: "I feel sick.", transcr: "ай фил сик" },
        { ru: "У меня кружится голова.", en: "I feel dizzy.", transcr: "ай фил дизи" },
        { ru: "У меня болит здесь.", en: "It hurts here.", transcr: "ит хётс хиэ" },
        { ru: "У меня температура.", en: "I've got a temperature.", transcr: "айв гот э тэмпричэ" },
        { ru: "Я принимаю лекарства от…", en: "I'm on medication for…", transcr: "айм он мэдикэйшн фо" },
        { ru: "У меня диабет.", en: "I'm diabetic.", transcr: "айм дайэбетик" },
        // — Симптомы —
        { sec: "Симптомы", ru: "У меня болит голова.", en: "I've got a headache.", transcr: "айв гот э хэдэйк" },
        { ru: "У меня болит горло.", en: "I've got a sore throat.", transcr: "айв гот э со сроут" },
        { ru: "У меня кашель.", en: "I've got a cough.", transcr: "айв гот э коф" },
        { ru: "У меня простуда.", en: "I've got a cold.", transcr: "айв гот э колд" },
        { ru: "У меня болит живот.", en: "I've got a stomach ache.", transcr: "айв гот э стамэк эйк" },
        { ru: "У меня расстройство желудка.", en: "I've got an upset stomach.", transcr: "айв гот эн апсэт стамэк" },
        { ru: "У меня болит спина.", en: "I've got backache.", transcr: "айв гот бэкэйк" },
        { ru: "У меня аллергия на пенициллин.", en: "I'm allergic to penicillin.", transcr: "айм элёджик тэ пэнисилин" },
        // — Аптека —
        { sec: "Аптека", ru: "Где ближайшая аптека?", en: "Where's the nearest chemist's?", transcr: "уэаз зэ ниэрэст кемистс" },
        { ru: "Дайте что-нибудь от головной боли.", en: "Could I have something for a headache?", transcr: "куд ай хэв самсин фо э хэдэйк" },
        { ru: "Что-нибудь от кашля, пожалуйста.", en: "Something for a cough, please.", transcr: "самсин фо э коф плиз" },
        { ru: "Что-нибудь от температуры.", en: "Something for a fever, please.", transcr: "самсин фо э фивэ плиз" },
        { ru: "Мне нужно обезболивающее.", en: "I need some painkillers.", transcr: "ай нид сам пэйнкилэз" },
        { ru: "Как принимать это лекарство?", en: "How do I take this medicine?", transcr: "хау ду ай тэйк зис мэдсин" },
        { ru: "До еды или после?", en: "Before or after meals?", transcr: "бифо о афтэ милз" },
        { ru: "Сколько раз в день?", en: "How many times a day?", transcr: "хау мэни таймз э дэй" },
        { ru: "Вот мой рецепт.", en: "Here's my prescription.", transcr: "хиэз май прискрипшн" },
        // — Зубной —
        { sec: "Зубной", ru: "У меня болит зуб.", en: "I've got toothache.", transcr: "айв гот тусэйк" },
        { ru: "Я потерял пломбу.", en: "I've lost a filling.", transcr: "айв лост э филин" },
        // — Срочно —
        { sec: "Срочно", ru: "Это срочно.", en: "It's an emergency.", transcr: "итс эн имёджэнси" },
        { ru: "Вызовите скорую!", en: "Call an ambulance!", transcr: "кол эн эмбьюлэнс" },
        { ru: "Позвоните 999.", en: "Call 999.", transcr: "кол найн найн найн" },
        { ru: "Где ближайшая больница?", en: "Where's the nearest hospital?", transcr: "уэаз зэ ниэрэст хоспитл" },
      ],
    },
    {
      id: "problems",
      icon: "⚠️",
      title_ru: "Проблемы и помощь",
      phrases: [
        // — Срочная помощь —
        { sec: "Срочная помощь", ru: "Помогите!", en: "Help!", transcr: "хэлп" },
        { ru: "Вы можете мне помочь?", en: "Can you help me?", transcr: "кэн ю хэлп ми" },
        { ru: "Осторожно!", en: "Look out!", transcr: "лук аут" },
        { ru: "Пожар!", en: "Fire!", transcr: "файэ" },
        { ru: "Позвоните 999.", en: "Call 999.", transcr: "кол найн найн найн" },
        { ru: "Оставьте меня в покое!", en: "Leave me alone!", transcr: "лив ми элоун" },
        // — Кража и пропажа —
        { sec: "Кража и пропажа", ru: "Меня ограбили.", en: "I've been robbed.", transcr: "айв бин робд" },
        { ru: "У меня украли кошелёк.", en: "My wallet has been stolen.", transcr: "май уолит хэз бин стоулэн" },
        { ru: "У меня украли сумку.", en: "My bag has been stolen.", transcr: "май бэг хэз бин стоулэн" },
        { ru: "Я потерял паспорт.", en: "I've lost my passport.", transcr: "айв лост май паспот" },
        { ru: "Я потерял телефон.", en: "I've lost my phone.", transcr: "айв лост май фоун" },
        { ru: "Вызовите полицию!", en: "Call the police!", transcr: "кол зэ пэлис" },
        { ru: "Где полицейский участок?", en: "Where's the police station?", transcr: "уэаз зэ пэлис стэйшн" },
        { ru: "Где бюро находок?", en: "Where's the lost property office?", transcr: "уэаз зэ лост пропэти офис" },
        { ru: "Я хочу заявить о краже.", en: "I'd like to report a theft.", transcr: "айд лайк тэ рипот э сэфт" },
        // — Потерялся —
        { sec: "Потерялся", ru: "Я заблудился.", en: "I'm lost.", transcr: "айм лост" },
        { ru: "Я потерял свою группу.", en: "I've lost my group.", transcr: "айв лост май груп" },
        { ru: "Я не могу найти свой отель.", en: "I can't find my hotel.", transcr: "ай кант файнд май хоутэл" },
        { ru: "Потерялся ребёнок.", en: "A child is missing.", transcr: "э чайлд из мисин" },
        // — Языковой барьер —
        { sec: "Языковой барьер", ru: "Я не говорю по-английски.", en: "I don't speak English.", transcr: "ай доунт спик инглиш" },
        { ru: "Здесь кто-нибудь говорит по-русски?", en: "Does anyone here speak Russian?", transcr: "даз эниуан хиэ спик рашн" },
        { ru: "Я хочу позвонить в посольство.", en: "I'd like to call my embassy.", transcr: "айд лайк тэ кол май эмбэси" },
        { ru: "Напишите это, пожалуйста.", en: "Could you write it down, please?", transcr: "куд ю райт ит даун плиз" },
      ],
    },
    {
      id: "about",
      icon: "🙋",
      title_ru: "О себе",
      phrases: [
        // — Имя и возраст —
        { sec: "Имя и возраст", ru: "Меня зовут…", en: "My name is…", transcr: "май нэйм из" },
        { ru: "Как ваше имя?", en: "What's your first name?", transcr: "уотс ё фёст нэйм" },
        { ru: "Как ваша фамилия?", en: "What's your surname?", transcr: "уотс ё сёнэйм" },
        { ru: "Мне тридцать лет.", en: "I'm thirty years old.", transcr: "айм сёти йиэз оулд" },
        { ru: "Я из России.", en: "I'm from Russia.", transcr: "айм фром раша" },
        // — Где я живу —
        { sec: "Где я живу", ru: "Я живу в Москве.", en: "I live in Moscow.", transcr: "ай лив ин москоу" },
        { ru: "Я живу в большом городе.", en: "I live in a big city.", transcr: "ай лив ин э биг сити" },
        { ru: "Я из небольшого города.", en: "I come from a small town.", transcr: "ай кам фром э смол таун" },
        // — Семейное положение —
        { sec: "Семейное положение", ru: "Я женат. / Я замужем.", en: "I'm married.", transcr: "айм мэрид" },
        { ru: "Я не женат. / Я не замужем.", en: "I'm single.", transcr: "айм сингл" },
        { ru: "У меня двое детей.", en: "I have two children.", transcr: "ай хэв ту чилдрэн" },
        // — Работа —
        { sec: "Работа", ru: "Кем вы работаете?", en: "What do you do?", transcr: "уот ду ю ду" },
        { ru: "Я работаю инженером.", en: "I work as an engineer.", transcr: "ай уёк эз эн энджиниэ" },
        { ru: "Я работаю в офисе.", en: "I work in an office.", transcr: "ай уёк ин эн офис" },
        { ru: "Я на пенсии.", en: "I'm retired.", transcr: "айм ритайэд" },
        // — Знакомство поближе —
        { sec: "Знакомство поближе", ru: "Я здесь впервые.", en: "This is my first time here.", transcr: "зис из май фёст тайм хиэ" },
        { ru: "Мне здесь очень нравится.", en: "I really like it here.", transcr: "ай риэли лайк ит хиэ" },
        { ru: "Вот мой номер телефона.", en: "Here's my phone number.", transcr: "хиэз май фоун намбэ" },
        { ru: "Давайте поддерживать связь.", en: "Let's keep in touch.", transcr: "летс кип ин тач" },
      ],
    },
    {
      id: "family",
      icon: "👨‍👩‍👧",
      title_ru: "Семья",
      phrases: [
        // — Моя семья —
        { sec: "Моя семья", ru: "Это моя жена.", en: "This is my wife.", transcr: "зис из май уайф" },
        { ru: "Это мой муж.", en: "This is my husband.", transcr: "зис из май хазбэнд" },
        { ru: "Это мои родители.", en: "These are my parents.", transcr: "зиз а май пэарэнтс" },
        { ru: "Мой брат и моя сестра.", en: "My brother and my sister.", transcr: "май бразэ энд май систэ" },
        { ru: "Это мой друг.", en: "This is my friend.", transcr: "зис из май фрэнд" },
        { ru: "Вот фотография моей семьи.", en: "Here's a photo of my family.", transcr: "хиэз э фоутоу оф май фэмили" },
        // — Дети —
        { sec: "Дети", ru: "Это мой сын.", en: "This is my son.", transcr: "зис из май сан" },
        { ru: "Это моя дочь.", en: "This is my daughter.", transcr: "зис из май дотэ" },
        { ru: "У вас есть дети?", en: "Do you have children?", transcr: "ду ю хэв чилдрэн" },
        { ru: "У меня один ребёнок.", en: "I have one child.", transcr: "ай хэв уан чайлд" },
        { ru: "Я единственный ребёнок.", en: "I'm an only child.", transcr: "айм эн оунли чайлд" },
        { ru: "Сколько лет вашему сыну?", en: "How old is your son?", transcr: "хау олд из ё сан" },
        // — Родственники —
        { sec: "Родственники", ru: "Мои дедушка и бабушка.", en: "My grandfather and grandmother.", transcr: "май грэндфазэ энд грэндмазэ" },
        { ru: "Мои внук и внучка.", en: "My grandson and granddaughter.", transcr: "май грэндсан энд грэнддотэ" },
        { ru: "Мои дядя и тётя.", en: "My uncle and aunt.", transcr: "май анкл энд ант" },
      ],
    },
    {
      id: "education",
      icon: "🎓",
      title_ru: "Язык и учёба",
      phrases: [
        // — Языковая помощь —
        { sec: "Языковая помощь", ru: "Я изучаю английский.", en: "I'm learning English.", transcr: "айм лёнин инглиш" },
        { ru: "Я плохо говорю по-английски.", en: "I don't speak English very well.", transcr: "ай доунт спик инглиш вэри уэл" },
        { ru: "Здесь кто-нибудь говорит по-русски?", en: "Does anyone here speak Russian?", transcr: "даз эни-уан хиэ спик рашн" },
        { ru: "Как это пишется?", en: "How do you spell that?", transcr: "хау ду ю спэл зэт" },
        { ru: "Что это значит?", en: "What does that mean?", transcr: "уот даз зэт мин" },
        { ru: "Как сказать это по-английски?", en: "How do you say this in English?", transcr: "хау ду ю сэй зис ин инглиш" },
        { ru: "Напишите это, пожалуйста.", en: "Could you write it down, please?", transcr: "куд ю райт ит даун плиз" },
        { ru: "Я понимаю.", en: "I understand.", transcr: "ай андэстэнд" },
        { ru: "Извините, я не расслышал.", en: "Sorry, I didn't catch that.", transcr: "сори ай диднт кэч зэт" },
        { ru: "Помогите мне, пожалуйста.", en: "Could you help me, please?", transcr: "куд ю хэлп ми плиз" },
        // — Учёба —
        { sec: "Учёба", ru: "Я студент.", en: "I'm a student.", transcr: "айм э стьюдэнт" },
        { ru: "Я учусь в университете.", en: "I study at university.", transcr: "ай стади эт юнивёсити" },
        { ru: "Что вы изучаете?", en: "What do you study?", transcr: "уот ду ю стади" },
        { ru: "Я учу язык самостоятельно.", en: "I'm teaching myself.", transcr: "айм тичин майсэлф" },
        { ru: "Мне нужно больше практики.", en: "I need more practice.", transcr: "ай нид мо прэктис" },
      ],
    },
    {
      id: "measures",
      icon: "📏",
      title_ru: "Меры: длина, вес, объём",
      phrases: [
        // — Расстояние —
        { sec: "Расстояние", ru: "Как далеко это?", en: "How far is it?", transcr: "хау фа из ит" },
        { ru: "Здесь измеряют в милях.", en: "They use miles here.", transcr: "зэй юз майлз хиэ" },
        { ru: "Одна миля — около 1,6 км.", en: "A mile is about 1.6 kilometres.", transcr: "э майл из эбаут уан пойнт сикс киломитэз" },
        { ru: "Сколько это в километрах?", en: "How much is that in kilometres?", transcr: "хау мач из зэт ин киломитэз" },
        // — Вес —
        { sec: "Вес", ru: "Сколько это весит?", en: "How much does it weigh?", transcr: "хау мач даз ит уэй" },
        { ru: "Здесь вес в фунтах.", en: "They weigh things in pounds here.", transcr: "зэй уэй сингз ин паундз хиэ" },
        { ru: "Один фунт — около 450 граммов.", en: "A pound is about 450 grams.", transcr: "э паунд из эбаут фо хандрэд энд фифти грэмз" },
        { ru: "Полкило, пожалуйста.", en: "Half a kilo, please.", transcr: "хаф э килоу плиз" },
        // — Объём —
        { sec: "Объём", ru: "Пинту молока, пожалуйста.", en: "A pint of milk, please.", transcr: "э пайнт оф милк плиз" },
        { ru: "Одна пинта — примерно поллитра.", en: "A pint is about half a litre.", transcr: "э пайнт из эбаут хаф э литэ" },
        { ru: "Литр воды, пожалуйста.", en: "A litre of water, please.", transcr: "э литэ оф уотэ плиз" },
        { ru: "Сколько это в литрах?", en: "How much is that in litres?", transcr: "хау мач из зэт ин литэз" },
      ],
    },
    {
      id: "time",
      icon: "🕒",
      title_ru: "Время, дни, даты",
      phrases: [
        // — Который час —
        { sec: "Который час", ru: "Который час?", en: "What time is it?", transcr: "уот тайм из ит" },
        { ru: "Сейчас три часа.", en: "It's three o'clock.", transcr: "итс сри эклок" },
        { ru: "Половина пятого.", en: "It's half past four.", transcr: "итс хаф паст фо" },
        { ru: "Четверть шестого.", en: "It's quarter past five.", transcr: "итс куотэ паст файв" },
        { ru: "Без четверти семь.", en: "It's quarter to seven.", transcr: "итс куотэ тэ сэвн" },
        { ru: "В полдень.", en: "At midday.", transcr: "эт миддэй" },
        { ru: "В полночь.", en: "At midnight.", transcr: "эт миднайт" },
        // — Когда —
        { sec: "Когда", ru: "Сегодня.", en: "Today.", transcr: "тэдэй" },
        { ru: "Завтра.", en: "Tomorrow.", transcr: "тэмороу" },
        { ru: "Вчера.", en: "Yesterday.", transcr: "йестэдэй" },
        { ru: "Сейчас.", en: "Now.", transcr: "нау" },
        { ru: "Позже.", en: "Later.", transcr: "лэйтэ" },
        { ru: "Утром.", en: "In the morning.", transcr: "ин зэ монин" },
        { ru: "Днём.", en: "In the afternoon.", transcr: "ин зи афтэнун" },
        { ru: "Вечером.", en: "In the evening.", transcr: "ин зи ивнин" },
        { ru: "На этой неделе.", en: "This week.", transcr: "зис уик" },
        // — Дни недели —
        { sec: "Дни недели", ru: "Понедельник, вторник.", en: "Monday, Tuesday.", transcr: "мандэй, тьюздэй" },
        { ru: "Среда, четверг.", en: "Wednesday, Thursday.", transcr: "уэнздэй, сёздэй" },
        { ru: "Пятница, суббота.", en: "Friday, Saturday.", transcr: "фрайдэй, сэтэдэй" },
        { ru: "Воскресенье.", en: "Sunday.", transcr: "сандэй" },
        { ru: "В выходные.", en: "At the weekend.", transcr: "эт зэ уикэнд" },
      ],
    },
    {
      id: "months",
      icon: "📅",
      title_ru: "Месяцы и сезоны",
      phrases: [
        // — Месяцы —
        { sec: "Месяцы", ru: "Январь.", en: "January.", transcr: "джэньюэри" },
        { ru: "Февраль.", en: "February.", transcr: "фэбруэри" },
        { ru: "Март.", en: "March.", transcr: "мач" },
        { ru: "Апрель.", en: "April.", transcr: "эйприл" },
        { ru: "Май.", en: "May.", transcr: "мэй" },
        { ru: "Июнь.", en: "June.", transcr: "джун" },
        { ru: "Июль.", en: "July.", transcr: "джулай" },
        { ru: "Август.", en: "August.", transcr: "огэст" },
        { ru: "Сентябрь.", en: "September.", transcr: "сэптэмбэ" },
        { ru: "Октябрь.", en: "October.", transcr: "октоубэ" },
        { ru: "Ноябрь.", en: "November.", transcr: "нэвэмбэ" },
        { ru: "Декабрь.", en: "December.", transcr: "дисэмбэ" },
        // — Времена года —
        { sec: "Времена года", ru: "Весна.", en: "Spring.", transcr: "сприн" },
        { ru: "Лето.", en: "Summer.", transcr: "самэ" },
        { ru: "Осень.", en: "Autumn.", transcr: "отэм" },
        { ru: "Зима.", en: "Winter.", transcr: "уинтэ" },
        { ru: "Сухой сезон.", en: "Dry season.", transcr: "драй сизн" },
        { ru: "Сезон дождей.", en: "Rainy season.", transcr: "рэйни сизн" },
        // — Даты и сезоны в разговоре —
        { sec: "Даты и сезоны в разговоре", ru: "Какой сейчас месяц?", en: "What month is it?", transcr: "уот манс из ит" },
        { ru: "Сейчас апрель.", en: "It's April.", transcr: "итс эйприл" },
        { ru: "У меня день рождения в июле.", en: "My birthday is in July.", transcr: "май бёсдэй из ин джулай" },
        { ru: "В этом месяце.", en: "This month.", transcr: "зис манс" },
        { ru: "В следующем месяце.", en: "Next month.", transcr: "нэкст манс" },
        { ru: "В прошлом месяце.", en: "Last month.", transcr: "ласт манс" },
        { ru: "В прошлом году.", en: "Last year.", transcr: "ласт йиэ" },
        { ru: "В начале месяца.", en: "At the beginning of the month.", transcr: "эт зэ бигинин ов зэ манс" },
        { ru: "В конце месяца.", en: "At the end of the month.", transcr: "эт зи энд ов зэ манс" },
        { ru: "Высокий сезон.", en: "High season.", transcr: "хай сизн" },
        { ru: "Низкий сезон.", en: "Low season.", transcr: "лоу сизн" },
        { ru: "Лучшее время для поездки — весной.", en: "The best time to visit is in spring.", transcr: "зэ бэст тайм тэ визит из ин сприн" },
      ],
    },
    {
      id: "weather",
      icon: "🌦️",
      title_ru: "Погода",
      phrases: [
        // — Какая погода —
        { sec: "Какая погода", ru: "Какая сегодня погода?", en: "What's the weather like today?", transcr: "уотс зэ уэзэ лайк тэдэй" },
        { ru: "Солнечно.", en: "It's sunny.", transcr: "итс сани" },
        { ru: "Пасмурно.", en: "It's cloudy.", transcr: "итс клауди" },
        { ru: "Идёт дождь.", en: "It's raining.", transcr: "итс рэйнин" },
        { ru: "Идёт снег.", en: "It's snowing.", transcr: "итс сноуин" },
        { ru: "Туман.", en: "It's foggy.", transcr: "итс фоги" },
        { ru: "Ветрено.", en: "It's windy.", transcr: "итс уинди" },
        // — Тепло или холодно —
        { sec: "Тепло или холодно", ru: "Холодно.", en: "It's cold.", transcr: "итс коулд" },
        { ru: "Жарко.", en: "It's hot.", transcr: "итс хот" },
        { ru: "Тепло.", en: "It's warm.", transcr: "итс уом" },
        { ru: "Прохладно.", en: "It's chilly.", transcr: "итс чили" },
        { ru: "Какая температура?", en: "What's the temperature?", transcr: "уотс зэ тэмпричэ" },
        // — Прогноз —
        { sec: "Прогноз", ru: "Будет дождь?", en: "Is it going to rain?", transcr: "из ит гоуин тэ рэйн" },
        { ru: "Какой прогноз на завтра?", en: "What's the forecast for tomorrow?", transcr: "уотс зэ фокаст фо тэмороу" },
        { ru: "Мне нужен зонт.", en: "I need an umbrella.", transcr: "ай нид эн амбрэлэ" },
        { ru: "Какая прекрасная погода!", en: "What lovely weather!", transcr: "уот лавли уэзэ" },
      ],
    },
    {
      id: "colours",
      icon: "🎨",
      title_ru: "Цвета",
      phrases: [
        // — Основные цвета —
        { sec: "Основные цвета", ru: "Красный.", en: "Red.", transcr: "рэд" },
        { ru: "Оранжевый.", en: "Orange.", transcr: "ориндж" },
        { ru: "Жёлтый.", en: "Yellow.", transcr: "йелоу" },
        { ru: "Зелёный.", en: "Green.", transcr: "грин" },
        { ru: "Синий / голубой.", en: "Blue.", transcr: "блу" },
        { ru: "Фиолетовый.", en: "Purple.", transcr: "пёпл" },
        { ru: "Розовый.", en: "Pink.", transcr: "пинк" },
        { ru: "Чёрный.", en: "Black.", transcr: "блэк" },
        { ru: "Белый.", en: "White.", transcr: "уайт" },
        { ru: "Серый.", en: "Grey.", transcr: "грэй" },
        { ru: "Коричневый.", en: "Brown.", transcr: "браун" },
        // — Оттенки —
        { sec: "Оттенки", ru: "Светло-синий.", en: "Light blue.", transcr: "лайт блу" },
        { ru: "Тёмно-синий.", en: "Dark blue.", transcr: "дак блу" },
        { ru: "Светло-зелёный.", en: "Light green.", transcr: "лайт грин" },
        { ru: "Тёмно-зелёный.", en: "Dark green.", transcr: "дак грин" },
        { ru: "Бежевый.", en: "Beige.", transcr: "бэйж" },
        { ru: "Золотой.", en: "Gold.", transcr: "гоулд" },
        { ru: "Серебристый.", en: "Silver.", transcr: "силвэ" },
        { ru: "Бирюзовый.", en: "Turquoise.", transcr: "тёкойз" },
        { ru: "Тёмно-синий (морской).", en: "Navy blue.", transcr: "нэйви блу" },
        { ru: "Кремовый.", en: "Cream.", transcr: "крим" },
        // — Разговор о цвете —
        { sec: "Разговор о цвете", ru: "Какого это цвета?", en: "What colour is it?", transcr: "уот калэ из ит" },
        { ru: "Какой цвет вы хотите?", en: "What colour would you like?", transcr: "уот калэ уд ю лайк" },
        { ru: "У вас есть это другого цвета?", en: "Do you have it in another colour?", transcr: "ду ю хэв ит ин эназэ калэ" },
        { ru: "Мне нравится синий.", en: "I like the blue one.", transcr: "ай лайк зэ блу уан" },
        { ru: "У вас есть это более светлого оттенка?", en: "Do you have this in a lighter colour?", transcr: "ду ю хэв зис ин э лайтэ калэ" },
        { ru: "У вас есть это более тёмного оттенка?", en: "Do you have this in a darker colour?", transcr: "ду ю хэв зис ин э дакэ калэ" },
        { ru: "Для меня это слишком яркое.", en: "It's too bright for me.", transcr: "итс ту брайт фо ми" },
        { ru: "Я бы предпочёл что-то однотонное.", en: "I'd prefer something plain.", transcr: "айд прифё самсин плэйн" },
      ],
    },
    {
      id: "numbers",
      icon: "🔢",
      title_ru: "Числа",
      phrases: [
        // — Количественные числительные 0–12 —
        { sec: "Количественные числительные 0–12", ru: "Ноль.", en: "Zero.", transcr: "зиэроу" },
        { ru: "Один.", en: "One.", transcr: "уан" },
        { ru: "Два.", en: "Two.", transcr: "ту" },
        { ru: "Три.", en: "Three.", transcr: "сри" },
        { ru: "Четыре.", en: "Four.", transcr: "фо" },
        { ru: "Пять.", en: "Five.", transcr: "файв" },
        { ru: "Шесть.", en: "Six.", transcr: "сикс" },
        { ru: "Семь.", en: "Seven.", transcr: "сэвн" },
        { ru: "Восемь.", en: "Eight.", transcr: "эйт" },
        { ru: "Девять.", en: "Nine.", transcr: "найн" },
        { ru: "Десять.", en: "Ten.", transcr: "тэн" },
        { ru: "Одиннадцать.", en: "Eleven.", transcr: "илэвн" },
        { ru: "Двенадцать.", en: "Twelve.", transcr: "туэлв" },
        // — От 13 до 20 —
        { sec: "От 13 до 20", ru: "Тринадцать.", en: "Thirteen.", transcr: "сётин" },
        { ru: "Четырнадцать.", en: "Fourteen.", transcr: "фотин" },
        { ru: "Пятнадцать.", en: "Fifteen.", transcr: "фифтин" },
        { ru: "Шестнадцать.", en: "Sixteen.", transcr: "сикстин" },
        { ru: "Семнадцать.", en: "Seventeen.", transcr: "сэвнтин" },
        { ru: "Восемнадцать.", en: "Eighteen.", transcr: "эйтин" },
        { ru: "Девятнадцать.", en: "Nineteen.", transcr: "найнтин" },
        { ru: "Двадцать.", en: "Twenty.", transcr: "туэнти" },
        // — Десятки —
        { sec: "Десятки", ru: "Тридцать.", en: "Thirty.", transcr: "сёти" },
        { ru: "Сорок.", en: "Forty.", transcr: "фоти" },
        { ru: "Пятьдесят.", en: "Fifty.", transcr: "фифти" },
        { ru: "Шестьдесят.", en: "Sixty.", transcr: "сиксти" },
        { ru: "Семьдесят.", en: "Seventy.", transcr: "сэвнти" },
        { ru: "Восемьдесят.", en: "Eighty.", transcr: "эйти" },
        { ru: "Девяносто.", en: "Ninety.", transcr: "найнти" },
        // — Большие числа —
        { sec: "Большие числа", ru: "Сто.", en: "A hundred.", transcr: "э хандрэд" },
        { ru: "Сто пятьдесят.", en: "A hundred and fifty.", transcr: "э хандрэд энд фифти" },
        { ru: "Тысяча.", en: "A thousand.", transcr: "э саузэнд" },
        { ru: "Десять тысяч.", en: "Ten thousand.", transcr: "тэн саузэнд" },
        { ru: "Миллион.", en: "A million.", transcr: "э мильен" },
        // — Порядковые числительные —
        { sec: "Порядковые числительные", ru: "Первый.", en: "First.", transcr: "фёст" },
        { ru: "Второй.", en: "Second.", transcr: "сэкэнд" },
        { ru: "Третий.", en: "Third.", transcr: "сёд" },
        { ru: "Четвёртый.", en: "Fourth.", transcr: "фос" },
        { ru: "Пятый.", en: "Fifth.", transcr: "фифс" },
        { ru: "Десятый.", en: "Tenth.", transcr: "тэнс" },
        // — Дроби и проценты —
        { sec: "Дроби и проценты", ru: "Половина.", en: "A half.", transcr: "э хаф" },
        { ru: "Треть.", en: "A third.", transcr: "э сёд" },
        { ru: "Четверть.", en: "A quarter.", transcr: "э куотэ" },
        { ru: "Десять процентов.", en: "Ten per cent.", transcr: "тэн пэ сэнт" },
        // — Числа в разговоре —
        { sec: "Числа в разговоре", ru: "Сколько (штук)?", en: "How many?", transcr: "хау мэни" },
        { ru: "Столик на двоих, пожалуйста.", en: "A table for two, please.", transcr: "э тэйбл фо ту плиз" },
        { ru: "Мне тридцать лет.", en: "I'm thirty years old.", transcr: "айм сёти йиэз оулд" },
        { ru: "Мой номер телефона...", en: "My phone number is…", transcr: "май фоун намбэ из" },
      ],
    },
  ];

  if (typeof module !== "undefined" && module.exports) module.exports = PHRASEBOOK;
  root.PHRASEBOOK = PHRASEBOOK;
})(typeof window !== "undefined" ? window : this);
